### ISSUE TITLE
Segfault using complex<double> tensor contraction

### ISSUE THREAD

**Issue by mganahl** [springer13/tcl#1]
A modification of the example code example/contraction.cpp to `complex<double>` for the contraction of two tensors crashes with a segfault during the contraction. I compiled with g++ 5.4.0 on a linux machine (Ubuntu 16.04); the code was linked with openBLAS.
The segfault happens for hptt built using make scalar and using make avx.
Segfault occurs for the specific choice of tensor-dimensions as given in contraction.cpp; for most other  choices the program finished fine.

contraction.cpp

#include <stdlib.h>
#include <iostream>
#include <complex>
#include <cstdlib>
#include <tcl.h>
using namespace std;
using std::cout;
using std::endl;

double c_rand(double min,double max){
  assert(min<=max);
  return min +fabs(max-min)*rand()/RAND_MAX;
}

int main(int argc, char** argv)
{
   tcl::sizeType i1 = 110;
   tcl::sizeType i2 = 100;
   tcl::sizeType i3 = 120;
   tcl::sizeType i4 = 131;
   
   tcl::sizeType b1 = 98;
   tcl::sizeType b2 = i1;
   tcl::sizeType b3 = i4;   

  ` complex<double>`*dataA=new `complex<double>`[i1 * i2 * i3 * i4];
   `complex<double>`*dataB=new `complex<double>`[b1 * b2 * b3];
   `complex<double>`*dataC=new `complex<double>`[b1 * i2 * i3];
 
   // Initialize tensors (data is not owned by the tensors)
   `tcl::Tensor<complex<double> >` A({i1,i2,i3,i4}, dataA);
   `tcl::Tensor<complex<double> >` B({b1,b2,b3}, dataB);
   `tcl::Tensor<complex<double> >` C({b1,i2,i3}, dataC);
   
   // Data initialization
#pragma omp parallel for
   for(int i=0; i < A.getTotalSize(); ++i)
     dataA[i] = `complex<double>(c_rand(-1.0,1.0),c_rand(-1.0,1.0));`
#pragma omp parallel for
   for(int i=0; i < B.getTotalSize(); ++i)
     dataB[i] =  `complex<double>(c_rand(-1.0,1.0),c_rand(-1.0,1.0));`
#pragma omp parallel for
   for(int i=0; i < C.getTotalSize(); ++i)
     dataC[i] = `complex<double>(c_rand(-1.0,1.0),c_rand(-1.0,1.0));`
   cout<<"finished init"<<endl;
   `complex<double>` alpha = `complex<double>`(1.0);
   `complex<double>` beta= `complex<double>`(0.0);
   auto err = tcl::tensorMult<`complex<double>` >( alpha, A["i1,i2,i3,i4"], B["b1,i1,i4"], beta, C["b1,i2,i3"] );
   if( err != tcl::SUCCESS ){
      printf("ERROR: %s\n", tcl::getErrorString(err));
      exit(-1);
   }

   return 0;
}

**Comment by springer13** [comment]
I just fixed the bug, thanks for reporting it!
I'll close this issue for now.
Please let me know if you run into any other problems.
